### ISSUE TITLE
ImportError: cannot import name 'ShardedDDPOption' from 'transformers.trainer_utils'

### ISSUE THREAD

**Issue by ubermenchh** [intel/intel-extension-for-transformers#866]
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[<ipython-input-5-c8ed222d4e1f>](https://localhost:8080/#) in <cell line: 15>()
     13 from intel_extension_for_transformers.transformers import OptimizedModel, QuantizationConfig
     14 from intel_extension_for_transformers.transformers import metrics as nlp_metrics
---> 15 from intel_extension_for_transformers.transformers.trainer import NLPSeq2SeqTrainer
     16 from transformers import (
     17     AutoConfig,

[/content/itrex/intel_extension_for_transformers/transformers/trainer.py](https://localhost:8080/#) in <module>
     66     nested_numpify,
     67 )
---> 68 from transformers.trainer_utils import (
     69     HPSearchBackend,
     70     ShardedDDPOption,

ImportError: cannot import name 'ShardedDDPOption' from 'transformers.trainer_utils' (/usr/local/lib/python3.10/dist-packages/transformers/trainer_utils.py)

**Comment by XinyuYe-Intel** [comment]
Hi @ubermenchh , this issue is caused by the deprecation of `ShardedDDPOption` in transformers since version 4.35.0.
We are working to fix this issue, meanwhile, you can try lower versioned transformers, e.g. v4.34.1.

**Comment by ubermenchh** [comment]
Yeah its working with `4.34.1`. Thanks

**Comment by ubermenchh** [comment]
Yeah its working with 4.34.1. Thanks
